image: node:latest

stages:
  - lint
  - build
  - test

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - npm install
  cache:
    paths:
      - node_modules/
lint:
  stage: lint
  script: npm run lint

test:
  stage: test
  script: npm test
